menu:
- {name: 'Experience', url: '/cv'}
- {name: 'DS Projects', url: '/projects'}
- {name: 'Courses', url: '/courses'}
- {name: 'About', url: '/me'}

me:
- {name: 'Tiego Tshehla', title: 'Data Scientist', department: 'Data Science', office: 'Some office', company_address: Company Address', phone: '(000) 000-0000', email: 'hello@company.com', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}

courses:
- {name: 'certifications', url: '/certifications.md'}

social:
- {icon: 'github', link: 'https://github.com/tiegoct'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/tiegotshehla'}
#- {icon: 'github', link: 'https://github.com/tiegot'}
#- {icon: 'twitter', link: 'https://twitter.com/whereistiego'}
#- {icon: 'instagram', link: 'https://instagram.com/tiegoct'}

contacts:
- {name: 'Contact 1', title: 'Lead Person', department: 'Data Science', office: 'Some office', company_address: 'address', phone: '(000) 000-0000', email: 'hello@company.com', image: 'assets/img/contact.jpg'}
