menu:
- {name: 'me', url: '/me'}
- {name: 'DS projects', url: '/projects'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}
- {name: 'art projects', url: '/art'}

me:
- {name: 'Tiego Tshehla', title: 'Data Scientist', department: 'Data Science', office: 'Some office', company_address: Company Address', phone: '(000) 000-0000', email: 'hello@company.com', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}

social:
- {icon: 'github', link: 'https://github.com/tiegoct'}
#- {icon: 'github', link: 'https://github.com/tiegot'}
#- {icon: 'twitter', link: 'https://twitter.com/whereistiego'}
#- {icon: 'instagram', link: 'https://instagram.com/tiegoct'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/tiegotshehla'}

contacts:
- {name: 'Contact 1', title: 'Lead Person', department: 'Data Science', office: 'Some office', company_address: 'address', phone: '(000) 000-0000', email: 'hello@company.com', image: 'assets/img/contact.jpg'}
