menu:
- {name: 'Experience', url: '/cv'}
- {name: 'Projects', url: '/projects'}
- {name: 'Courses', url: '/courses'}
# - {name: 'About', url: '/me'}
- {name: 'Contact', url: '/contact'}

me:
- {name: 'Tiego Tshehla', title: 'Data Scientist', department: 'Data Science', office: 'Some office', company_address: Company Address', phone: '(000) 000-0000', email: 'hello@company.com', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}

courses:
- {name: 'Certifications', url: '/certifications'}

social:
- {icon: 'github', link: 'https://github.com/tiegoct'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/tiegotshehla'}
#- {icon: 'github', link: 'https://github.com/tiegot'}
#- {icon: 'twitter', link: 'https://twitter.com/whereistiego'}
#- {icon: 'instagram', link: 'https://instagram.com/tiegoct'}

contacts:
- {name: 'Tiego Tshehla', title: 'Data Scientist', department: 'Data Science/Solutions', office: 'Rosebank', company_address: 'The Mall offices', phone: 'Too much spam - please use the LinkedIn link', email: 'https://linkedin.com/in/tiegotshehla', image: 'assets/img/contact.jpg'}
